#  SURELY THERE IS A BETTER WAY TO DO THIS??

userInput = input("Enter some characters: ")

a = userInput.lower().count("a")
b = userInput.lower().count("b")
c = userInput.lower().count("c")
d = userInput.lower().count("d")
e = userInput.lower().count("e")
f = userInput.lower().count("f")
g = userInput.lower().count("g")
h = userInput.lower().count("h")
i = userInput.lower().count("i")
j = userInput.lower().count("j")
k = userInput.lower().count("k")
l = userInput.lower().count("l")
m = userInput.lower().count("m")
n = userInput.lower().count("n")
o = userInput.lower().count("o")
p = userInput.lower().count("p")
q = userInput.lower().count("q")
r = userInput.lower().count("r")
s = userInput.lower().count("s")
t = userInput.lower().count("t")
u = userInput.lower().count("u")
v = userInput.lower().count("v")
w = userInput.lower().count("w")
x = userInput.lower().count("x")
y = userInput.lower().count("y")
z = userInput.lower().count("z")

print(f"a: {a}")
print(f"b: {b}")
print(f"c: {c}")
print(f"d: {d}")
print(f"e: {e}")
print(f"f: {f}")
print(f"g: {g}")
print(f"h: {h}")
print(f"i: {i}")
print(f"j: {j}")
print(f"k: {k}")
print(f"l: {l}")
print(f"m: {m}")
print(f"n: {n}")
print(f"o: {o}")
print(f"p: {p}")
print(f"q: {q}")
print(f"r: {r}")
print(f"s: {s}")
print(f"t: {t}")
print(f"u: {u}")
print(f"v: {v}")
print(f"w: {w}")
print(f"x: {x}")
print(f"y: {y}")
print(f"z: {z}")